import * as Dialog from '@radix-ui/react-dialog'; import * as Tabs from '@radix-ui/react-tabs'; import * as Select from '@radix-ui/react-select';
import { Check, ChevronDown, X } from 'lucide-react'; import { createContext, useContext, useState, type ReactNode } from 'react';
export const Button = ({ className = '', onClick, ...props }: React.ButtonHTMLAttributes<HTMLButtonElement>) => <button type="button" className={`btn ${className}`} onClick={onClick} {...props} />;
export function Timeframes({value,onChange}:{value:'1D'|'5D'|'1M'|'1Y';onChange:(v:any)=>void}){return <div className="timeframe" aria-label="Timeframe">{(['1D','5D','1M','1Y'] as const).map(v=><button key={v} type="button" aria-pressed={value===v} onClick={()=>onChange(v)}>{v}</button>)}</div>}
export function AppTabs({value,onChange,items,children}:{value:string;onChange:(v:string)=>void;items:{value:string;label:string}[];children:ReactNode}){return <Tabs.Root value={value} onValueChange={onChange}><Tabs.List className="tabs-list" aria-label="Analysis tabs">{items.map(x=><Tabs.Trigger key={x.value} value={x.value}>{x.label}</Tabs.Trigger>)}</Tabs.List>{children}</Tabs.Root>}
export function TabPanel({value,children}:{value:string;children:ReactNode}){return <Tabs.Content value={value}>{children}</Tabs.Content>}
export function SelectField({label,value,onChange,items}:{label:string;value:string;onChange:(value:string)=>void;items:{value:string;label:string}[]}){return <label className="field"><span>{label}</span><Select.Root value={value} onValueChange={onChange}><Select.Trigger className="select-trigger"><Select.Value/><ChevronDown size={14}/></Select.Trigger><Select.Portal><Select.Content className="listbox" position="popper"><Select.Viewport>{items.map(item=><Select.Item className="select-item" value={item.value} key={item.value}><Select.ItemText>{item.label}</Select.ItemText><Select.ItemIndicator><Check size={14}/></Select.ItemIndicator></Select.Item>)}</Select.Viewport></Select.Content></Select.Portal></Select.Root></label>}
type Toast={id:number;message:string;tone:'info'|'error'}; const ToastContext=createContext<{push:(message:string,tone?:Toast['tone'])=>void}>({push:()=>{}});
export function ToastProvider({children}:{children:ReactNode}){const [toasts,setToasts]=useState<Toast[]>([]);const push=(message:string,tone:Toast['tone']='info')=>{const id=Date.now();setToasts(x=>[...x,{id,message,tone}]);setTimeout(()=>setToasts(x=>x.filter(t=>t.id!==id)),4500)};return <ToastContext.Provider value={{push}}>{children}<div className="toast-region" aria-live="polite">{toasts.map(t=><div className="toast" key={t.id} role="status">{t.message}</div>)}</div></ToastContext.Provider>}
export const useToast=()=>useContext(ToastContext);
export function ConfirmDialog({open,onOpenChange,title,description,onConfirm,confirm='Delete',children}:{open:boolean;onOpenChange:(v:boolean)=>void;title:string;description:string;onConfirm:()=>void;confirm?:string;children?:ReactNode}){return <Dialog.Root open={open} onOpenChange={onOpenChange}><Dialog.Portal><Dialog.Overlay className="dialog-overlay"/><Dialog.Content className="dialog-content"><Dialog.Title>{title}</Dialog.Title><Dialog.Description className="note">{description}</Dialog.Description>{children}<div className="toolbar" style={{justifyContent:'flex-end',marginTop:20}}><Dialog.Close asChild><Button autoFocus onClick={()=>onOpenChange(false)}>Cancel</Button></Dialog.Close><Button className="danger" onClick={onConfirm}>{confirm}</Button></div></Dialog.Content></Dialog.Portal></Dialog.Root>}
export function Modal({open,onOpenChange,title,children}:{open:boolean;onOpenChange:(v:boolean)=>void;title:string;children:ReactNode}){return <Dialog.Root open={open} onOpenChange={onOpenChange}><Dialog.Portal><Dialog.Overlay className="dialog-overlay"/><Dialog.Content className="dialog-content" aria-describedby={undefined}><div style={{display:'flex',justifyContent:'space-between',gap:8}}><Dialog.Title>{title}</Dialog.Title><Dialog.Close asChild><Button className="ghost" aria-label="Close dialog" onClick={()=>onOpenChange(false)}><X size={17}/></Button></Dialog.Close></div>{children}</Dialog.Content></Dialog.Portal></Dialog.Root>}
