import type { Analytics, Auth, Fundamentals, Portfolio, PortfolioAnalytics, Position, PriceResponse, Timeframe, Instrument } from './types';
export class ApiError extends Error { constructor(public status:number, message:string, public code?:string){super(message)} }
let csrf = '';
const parseError = async (res:Response) => { const data = await res.json().catch(()=>null); const detail=data?.detail; return new ApiError(res.status, typeof detail==='string'?detail:detail?.message || `Request failed (${res.status})`, typeof detail==='object'?detail.code:undefined); };
async function request<T>(path:string, init:RequestInit={}, signal?:AbortSignal):Promise<T> { const headers=new Headers(init.headers); if (csrf && init.method && !['GET','HEAD'].includes(init.method)) headers.set('X-CSRF-Token', csrf); const r=await fetch(`/api/v1${path}`,{credentials:'same-origin',...init,headers,signal}); if (r.status === 401 && path !== '/auth/me') window.dispatchEvent(new Event('quant-stock:session-expired')); if(!r.ok) throw await parseError(r); return r.status===204 ? undefined as T : r.json() as Promise<T>; }
export const api={
 me: async()=>{const data=await request<Auth>('/auth/me');csrf=data.csrf_token;return data}, demo:async()=>{const data=await request<Auth>('/auth/demo',{method:'POST'});csrf=data.csrf_token;return data}, logout:()=>request<void>('/auth/logout',{method:'POST'}),
 universe:(q='',signal?:AbortSignal)=>request<{items:Instrument[];source:string;as_of:string|null}>(`/universe?q=${encodeURIComponent(q)}&limit=50`,{},signal),
 markets:(timeframe:Timeframe)=>request<{items:PriceResponse[];timeframe:Timeframe}>(`/markets?timeframe=${timeframe}`), price:(symbol:string,timeframe:Timeframe)=>request<PriceResponse>(`/stocks/${encodeURIComponent(symbol)}/prices?timeframe=${timeframe}`),
 analytics:(symbol:string,peers:string[],timeframe:Timeframe)=>request<Analytics>(`/stocks/${encodeURIComponent(symbol)}/analytics?peers=${encodeURIComponent(peers.join(','))}&timeframe=${timeframe}`), fundamentals:(symbol:string)=>request<Fundamentals>(`/stocks/${encodeURIComponent(symbol)}/fundamentals`),
 portfolios:()=>request<{items:Portfolio[]}>('/portfolios'), portfolio:(id:string)=>request<Portfolio>(`/portfolios/${encodeURIComponent(id)}`), createPortfolio:(name:string,positions:Position[],key:string)=>request<Portfolio>('/portfolios',{method:'POST',headers:{'Content-Type':'application/json','Idempotency-Key':key},body:JSON.stringify({name,positions})}), updatePortfolio:(id:string,name:string,positions:Position[],revision:number)=>request<Portfolio>(`/portfolios/${encodeURIComponent(id)}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({name,positions,revision})}), deletePortfolio:(id:string,revision:number)=>request<void>(`/portfolios/${encodeURIComponent(id)}?revision=${revision}`,{method:'DELETE'}), portfolioAnalytics:(positions:Position[])=>request<PortfolioAnalytics>('/portfolio-analytics',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({positions})})
};
