/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/demo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Demo Login */
        post: operations["demo_login_api_v1_auth_demo_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/universe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Universe */
        get: operations["universe_api_v1_universe_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/markets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Markets */
        get: operations["markets_api_v1_markets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stocks/{symbol}/prices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Prices */
        get: operations["prices_api_v1_stocks__symbol__prices_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stocks/{symbol}/analytics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Analytics */
        get: operations["analytics_api_v1_stocks__symbol__analytics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stocks/{symbol}/fundamentals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fundamentals */
        get: operations["fundamentals_api_v1_stocks__symbol__fundamentals_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/portfolio-analytics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Simulate */
        post: operations["simulate_api_v1_portfolio_analytics_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/portfolios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Portfolios */
        get: operations["list_portfolios_api_v1_portfolios_get"];
        put?: never;
        /** Create Portfolio */
        post: operations["create_portfolio_api_v1_portfolios_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/portfolios/{portfolio_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Portfolio */
        get: operations["get_portfolio_api_v1_portfolios__portfolio_id__get"];
        put?: never;
        post?: never;
        /** Delete Portfolio */
        delete: operations["delete_portfolio_api_v1_portfolios__portfolio_id__delete"];
        options?: never;
        head?: never;
        /** Update Portfolio */
        patch: operations["update_portfolio_api_v1_portfolios__portfolio_id__patch"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AnalyticsResponse */
        AnalyticsResponse: {
            /** Symbol */
            symbol: string;
            distribution: components["schemas"]["Distribution"];
            volume_profile: components["schemas"]["VolumeProfile"];
            comparison: components["schemas"]["Comparison"];
            capm: components["schemas"]["CAPM"];
            meta: components["schemas"]["Metadata"];
        };
        /** AuthResponse */
        AuthResponse: {
            user: components["schemas"]["User"];
            /** Csrf Token */
            csrf_token: string;
            /**
             * Mode
             * @enum {string}
             */
            mode: "demo" | "research" | "production";
        };
        /** Bar */
        Bar: {
            /** Time */
            time: string;
            /** Open */
            open?: number | null;
            /** High */
            high?: number | null;
            /** Low */
            low?: number | null;
            /** Close */
            close?: number | null;
            /** Volume */
            volume?: number | null;
        };
        /** CAPM */
        CAPM: {
            /** Beta */
            beta: number | null;
            /** Risk Free Rate */
            risk_free_rate: number | null;
            /** Market Return */
            market_return: number | null;
            /** Actual Return */
            actual_return: number | null;
            /** Expected Return */
            expected_return: number | null;
            /** Alpha */
            alpha: number | null;
            /** Current Price */
            current_price: number | null;
            /** Scenario Price */
            scenario_price: number | null;
            /** Sample Count */
            sample_count: number;
            /** Notes */
            notes: string[];
        };
        /** Comparison */
        Comparison: {
            /** Symbols */
            symbols: string[];
            /** Series */
            series: components["schemas"]["Series"][];
            /** Correlations */
            correlations: components["schemas"]["Correlation"][];
            /** Notes */
            notes: string[];
        };
        /** Consensus */
        Consensus: {
            /** Buy */
            buy?: number | null;
            /** Hold */
            hold?: number | null;
            /** Sell */
            sell?: number | null;
            /** Target Low */
            target_low?: number | null;
            /** Target Mean */
            target_mean?: number | null;
            /** Target High */
            target_high?: number | null;
            /** Analyst Count */
            analyst_count?: number | null;
        };
        /** Correlation */
        Correlation: {
            /** X */
            x: string;
            /** Y */
            y: string;
            /** Value */
            value: number | null;
            /** Sample Count */
            sample_count: number;
        };
        /** Distribution */
        Distribution: {
            /** Daily Mean */
            daily_mean: number | null;
            /** Daily Volatility */
            daily_volatility: number | null;
            /** Annual Return */
            annual_return: number | null;
            /** Annual Volatility */
            annual_volatility: number | null;
            /** Win Rate */
            win_rate: number | null;
            /** Sample Count */
            sample_count: number;
            /** Returns */
            returns: components["schemas"]["Point"][];
            /** Histogram */
            histogram: components["schemas"]["HistogramBin"][];
            /** Notes */
            notes: string[];
        };
        /** Estimate */
        Estimate: {
            /** Period */
            period: string;
            /** Revenue */
            revenue?: number | null;
            /** Eps */
            eps?: number | null;
        };
        /** FlowLink */
        FlowLink: {
            /** Source */
            source: string;
            /** Target */
            target: string;
            /** Value */
            value: number;
        };
        /** FlowStep */
        FlowStep: {
            /** Label */
            label: string;
            /** Value */
            value: number | null;
        };
        /** FundamentalMetrics */
        FundamentalMetrics: {
            /** Price */
            price?: number | null;
            /** Market Cap */
            market_cap?: number | null;
            /** Pe */
            pe?: number | null;
            /** Pb */
            pb?: number | null;
            /** Eps */
            eps?: number | null;
            /** Beta */
            beta?: number | null;
            /** Sharpe 6M */
            sharpe_6m?: number | null;
            /** Capm Target */
            capm_target?: number | null;
        };
        /** FundamentalsResponse */
        FundamentalsResponse: {
            /** Symbol */
            symbol: string;
            metrics: components["schemas"]["FundamentalMetrics"];
            /** Quarters */
            quarters: components["schemas"]["Quarter"][];
            estimate: components["schemas"]["Estimate"] | null;
            statements: components["schemas"]["Statements"];
            consensus: components["schemas"]["Consensus"];
            income_flow: components["schemas"]["IncomeFlow"];
            meta: components["schemas"]["Metadata"];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HistogramBin */
        HistogramBin: {
            /** Low */
            low: number;
            /** High */
            high: number;
            /** Count */
            count: number;
        };
        /** IncomeFlow */
        IncomeFlow: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "sankey" | "waterfall" | "unavailable";
            /** Nodes */
            nodes: string[];
            /** Links */
            links: components["schemas"]["FlowLink"][];
            /** Steps */
            steps: components["schemas"]["FlowStep"][];
            /** Notes */
            notes: string[];
        };
        /** Instrument */
        Instrument: {
            /** Symbol */
            symbol: string;
            /** Name */
            name: string;
            /** Sector */
            sector?: string | null;
            /**
             * Currency
             * @default USD
             */
            currency: string;
            /** Exchange */
            exchange?: string | null;
            /** Timezone */
            timezone?: string | null;
        };
        /** MarketResponse */
        MarketResponse: {
            /** Items */
            items: components["schemas"]["PriceResponse"][];
            /** Timeframe */
            timeframe: string;
        };
        /** Metadata */
        Metadata: {
            /** Source */
            source: string;
            /** As Of */
            as_of?: string | null;
            /** Retrieved At */
            retrieved_at?: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "fresh" | "stale" | "partial" | "unavailable" | "demo";
            /** Requested Window */
            requested_window?: string | null;
            /** Actual Start */
            actual_start?: string | null;
            /** Actual End */
            actual_end?: string | null;
            /** Currency */
            currency?: string | null;
            /** Interval */
            interval?: string | null;
            /** Sample Count */
            sample_count?: number | null;
            /** Notes */
            notes?: string[];
        };
        /** PerformancePoint */
        PerformancePoint: {
            /** Time */
            time: string;
            /** Portfolio */
            portfolio: number;
            /** Benchmark */
            benchmark: number;
        };
        /** Point */
        Point: {
            /** Time */
            time: string;
            /** Value */
            value: number | null;
        };
        /** PortfolioAnalyticsResponse */
        PortfolioAnalyticsResponse: {
            metrics: components["schemas"]["PortfolioMetrics"];
            /** Performance */
            performance: components["schemas"]["PerformancePoint"][];
            /** Sectors */
            sectors: components["schemas"]["Sector"][];
            meta: components["schemas"]["Metadata"];
        };
        /** PortfolioCreate */
        PortfolioCreate: {
            /** Positions */
            positions: components["schemas"]["Position"][];
            /** Name */
            name: string;
        };
        /** PortfolioList */
        PortfolioList: {
            /** Items */
            items: components["schemas"]["PortfolioRecord"][];
        };
        /** PortfolioMetrics */
        PortfolioMetrics: {
            /** Expected Return */
            expected_return: number | null;
            /** Volatility */
            volatility: number | null;
            /** Sharpe */
            sharpe: number | null;
            /** Beta */
            beta: number | null;
            /** Sample Count */
            sample_count: number;
            /** Notes */
            notes: string[];
        };
        /** PortfolioRecord */
        PortfolioRecord: {
            /** Positions */
            positions: components["schemas"]["Position"][];
            /** Name */
            name: string;
            /** Id */
            id: string;
            /** Revision */
            revision: number;
            /** Created At */
            created_at: string;
            /** Updated At */
            updated_at: string;
        };
        /** PortfolioUpdate */
        PortfolioUpdate: {
            /** Positions */
            positions: components["schemas"]["Position"][];
            /** Name */
            name: string;
            /** Revision */
            revision: number;
        };
        /** Position */
        Position: {
            /** Symbol */
            symbol: string;
            /** Weight Bps */
            weight_bps: number;
        };
        /** Positions */
        Positions: {
            /** Positions */
            positions: components["schemas"]["Position"][];
        };
        /** PriceResponse */
        PriceResponse: {
            instrument: components["schemas"]["Instrument"];
            /** Bars */
            bars: components["schemas"]["Bar"][];
            /** Last Price */
            last_price?: number | null;
            /** Change */
            change?: number | null;
            meta: components["schemas"]["Metadata"];
        };
        /** Quarter */
        Quarter: {
            /** Period */
            period: string;
            /** Revenue */
            revenue?: number | null;
            /** Eps */
            eps?: number | null;
            /** Gross Profit */
            gross_profit?: number | null;
            /** Operating Income */
            operating_income?: number | null;
            /** Net Income */
            net_income?: number | null;
            /** Cogs */
            cogs?: number | null;
            /** Opex */
            opex?: number | null;
            /** Taxes */
            taxes?: number | null;
            /** Gross Margin */
            gross_margin?: number | null;
            /** Operating Margin */
            operating_margin?: number | null;
            /** Net Margin */
            net_margin?: number | null;
            /** Revenue Qoq */
            revenue_qoq?: number | null;
            /** Revenue Yoy */
            revenue_yoy?: number | null;
            /** Eps Qoq */
            eps_qoq?: number | null;
            /** Eps Yoy */
            eps_yoy?: number | null;
        };
        /** Sector */
        Sector: {
            /** Sector */
            sector: string;
            /** Weight Bps */
            weight_bps: number;
            /** Holdings */
            holdings: components["schemas"]["Position"][];
        };
        /** Series */
        Series: {
            /** Symbol */
            symbol: string;
            /** Points */
            points: components["schemas"]["Point"][];
        };
        /** StatementRow */
        StatementRow: {
            /** Label */
            label: string;
            /** Value */
            value: number | null;
            /**
             * Unit
             * @enum {string}
             */
            unit: "currency" | "number" | "ratio" | "percent";
        };
        /** Statements */
        Statements: {
            /** Valuation */
            valuation: components["schemas"]["StatementRow"][];
            /** Income */
            income: components["schemas"]["StatementRow"][];
            /** Balance Cashflow */
            balance_cashflow: components["schemas"]["StatementRow"][];
        };
        /** UniverseResponse */
        UniverseResponse: {
            /** Items */
            items: components["schemas"]["Instrument"][];
            /** Source */
            source: string;
            /** As Of */
            as_of?: string | null;
        };
        /** User */
        User: {
            /** Id */
            id: string;
            /** Email */
            email: string;
            /** Name */
            name: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VolumeBin */
        VolumeBin: {
            /** Low */
            low: number;
            /** High */
            high: number;
            /** Volume */
            volume: number;
        };
        /** VolumeProfile */
        VolumeProfile: {
            /** Poc */
            poc: number | null;
            /** Vah */
            vah: number | null;
            /** Val */
            val: number | null;
            /** Coverage */
            coverage: number | null;
            /** Total Volume */
            total_volume: number | null;
            /** Bins */
            bins: components["schemas"]["VolumeBin"][];
            /** Notes */
            notes: string[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    demo_login_api_v1_auth_demo_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
        };
    };
    me_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
        };
    };
    logout_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    universe_api_v1_universe_get: {
        parameters: {
            query?: {
                q?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UniverseResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    markets_api_v1_markets_get: {
        parameters: {
            query?: {
                timeframe?: "1D" | "5D" | "1M" | "1Y";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MarketResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    prices_api_v1_stocks__symbol__prices_get: {
        parameters: {
            query?: {
                timeframe?: "1D" | "5D" | "1M" | "1Y";
            };
            header?: never;
            path: {
                symbol: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PriceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    analytics_api_v1_stocks__symbol__analytics_get: {
        parameters: {
            query?: {
                peers?: string;
                timeframe?: "1D" | "5D" | "1M" | "1Y";
            };
            header?: never;
            path: {
                symbol: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalyticsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    fundamentals_api_v1_stocks__symbol__fundamentals_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                symbol: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FundamentalsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    simulate_api_v1_portfolio_analytics_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Positions"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortfolioAnalyticsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_portfolios_api_v1_portfolios_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortfolioList"];
                };
            };
        };
    };
    create_portfolio_api_v1_portfolios_post: {
        parameters: {
            query?: never;
            header?: {
                "idempotency-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PortfolioCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortfolioRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_portfolio_api_v1_portfolios__portfolio_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                portfolio_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortfolioRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_portfolio_api_v1_portfolios__portfolio_id__delete: {
        parameters: {
            query: {
                revision: number;
            };
            header?: never;
            path: {
                portfolio_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_portfolio_api_v1_portfolios__portfolio_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                portfolio_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PortfolioUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortfolioRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
